### ISSUE TITLE
incompatible with mailchimp lists that include custom fields

### ISSUE THREAD

**Issue by macolo** [aldryn/aldryn-mailchimp#14]
I tried this add-on but when I add the subscription plugin to a page it only outputs the e-mail field. My mailchimp list however contains additional fields (like name) and custom fields (like birthday).

When I try to sign up I get a 250 error response from the mailchimp API (custom field data is missing).

Version: Aldryn Mailchimp 0.3.0 (from Aldryn Control Panel) - I did set the Mailchimp API Key.

**Comment by jmelett** [comment]
Thanks, for reporting - unfortunately we don't support custom fields yet.
However, feel free to send us a pull requests and we'd be happy to merge.
