### ISSUE TITLE
How to fetch campaigns on Aldryn test / live system

### ISSUE THREAD

**Issue by macolo** [aldryn/aldryn-mailchimp#15]
Using the command `./manage.py fetch_campaigns` works well but how is the campaign import working on the Aldryn test / live server where access to the command line is not possible...??)

Also, `fetch_campaigns` should probably be documented.

Also, campaigns should be imported automatically / periodically. This is probably more of a feature request than a bug.

**Comment by jmelett** [comment]
@macolo You'd have to push the DB from your local machine - or contact us so we can enable Celery for you on Aldryn, to run periodic jobs.
