### ISSUE TITLE
ImportError: No module named 'utils'

### ISSUE THREAD

**Issue by pinksharpii** [aldryn/aldryn-mailchimp#18]
I'm new to the Python and Django world so excuse me if this doesn't make the most sense. But I don't think this works with the latest version of Django or Django CMS. I'm not sure how to tell where this is breaking. 

But I did not see an installation guide of how to install this manually. Yesterday I tried to add it to my project with pip install. That worked fine but when I tried to make migrations it exploded. I wasn't sure if I did this wrong or maybe this app wasn't meant to be installed this way so I tried adding it the way it was meant to by adding the app to a project I created in the Divio control page. 

However, I'm getting the same error. My site is setup with Python 3.5 and the latest version of Django CMS. Is this a known issue? There shouldn't be any dependencies I need since those should have been added along with this, right?

<img width="824" alt="screen shot 2016-12-20 at 2 11 42 pm" src="https://cloud.githubusercontent.com/assets/3431241/21366180/40c4e0de-c6be-11e6-9047-3c2156ece99a.png">

**Comment by sneaker** [comment]
Hi @pinksharpii 

We also ran into this problem. Have you resolved it somehow?
Thx

**Comment by pinksharpii** [comment]
I forget exactly. Something wasn't included properly. Try looking through installed apps and making sure everything is included properly. And make sure you makemigrations. If all else fails maybe try uninstalling and reinstalling in case something got missed on install. I know that's not a lot to go off but I hope it helps. I ended up not using this plugin in the end.
